parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: siveli
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 93ec566501fa13da842766044ea9eb89f1baf606
    database_driver: pdo_mysql
    database_path: null
